import logging
import os
import pickle
import shutil
import sys

import numpy as np


def set_logging(work_dir=None, log_file=None):
    if log_file is not None:
        # create save directory and log file
        os.makedirs(work_dir, exist_ok=True)
        log_file_path = work_dir + '/' + log_file

        # basic logging definition
        logger = logging.getLogger()
        logger.setLevel(logging.INFO)

        # remove any previously defined loggers
        for handler in logger.handlers[:]:
            logger.removeHandler(handler)

        # print log messages to a log file
        fh = logging.FileHandler(log_file_path)
        fh_formatter = logging.Formatter(fmt='%(asctime)s %(message)s', datefmt='%d-%m-%Y %H:%M:%S')
        fh.setFormatter(fh_formatter)
        fh.setLevel(logging.INFO)
        logger.addHandler(fh)

        # print log messages to the console/termnal
        ch = logging.StreamHandler()
        ch_formatter = logging.Formatter('%(message)s')
        ch.setFormatter(ch_formatter)
        ch.setLevel(logging.INFO)
        logger.addHandler(ch)

        logging.info('setting log_file: ' + log_file_path)
    else:
        # print log messages to the console/terminal only (INFO, matching the file-handler branch)
        logging.basicConfig(format='%(message)s', level=logging.INFO)

        # disable the warnings generated by matplotlib when in interactive mode
        logging.getLogger('matplotlib').setLevel(logging.ERROR)

    # disable the warnings generated by submitit
    logging.getLogger("submitit").setLevel(logging.ERROR)

    return


def save_restart_file(status, work_dir, restart_file):
    """
    Pickle the status dict, stamping the current slurmcmc version for compatibility checking on load.
    The write is atomic (temp file + rename) so a job killed mid-save cannot corrupt an existing restart file.
    """
    from slurmcmc import __version__
    status = dict(status)  # shallow copy so the caller's dict is not mutated by the version stamp
    status['_slurmcmc_version'] = __version__
    os.makedirs(work_dir, exist_ok=True)
    restart_file_path = work_dir + '/' + restart_file
    tmp_file_path = restart_file_path + '.tmp'
    with open(tmp_file_path, 'wb') as f:
        pickle.dump(status, f)
    os.replace(tmp_file_path, restart_file_path)


def load_restart_file(work_dir, restart_file):
    """Load a pickled status dict. Warns if the file was saved by a different slurmcmc version."""
    from slurmcmc import __version__
    restart_file_path = work_dir + '/' + restart_file
    if os.path.exists(restart_file_path):
        with open(restart_file_path, 'rb') as f:
            status = pickle.load(f)
        saved_version = status.get('_slurmcmc_version', 'unknown')
        if saved_version != __version__:
            logging.warning(
                f"Restart file was saved with slurmcmc v{saved_version}, "
                f"current version is v{__version__}. Compatibility is not guaranteed."
            )
        return status
    else:
        err_msg = f'restart_file does not exist. restart_file_path={restart_file_path}'
        logging.error(err_msg)
        raise ValueError(err_msg)


def combine_args(arg, extra_arg=None):
    args = [arg]
    if extra_arg is not None:
        args += [extra_arg]
    return args


def save_extra_arg_to_file(work_dir, extra_arg):
    """Save extra_arg using pickle so arbitrary Python objects (numpy arrays, dicts, etc.) are supported."""
    if extra_arg is not None:
        extra_arg_file = os.path.join(work_dir, 'extra_arg.pkl')
        with open(extra_arg_file, 'wb') as f:
            pickle.dump(extra_arg, f)


def delete_directory(dir_path):
    if os.path.isdir(dir_path):
        shutil.rmtree(dir_path, ignore_errors=True)


def list_directories(path):
    return [d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d))]


def point_to_tuple(point):
    # convert to tuple even in case of 1d point
    return tuple(point) if isinstance(point, (list, set, np.ndarray)) else (point,)


def calc_dimension(point):
    if isinstance(point, (int, float, type(None))):
        return 1
    elif isinstance(point, (list, np.ndarray)):
        return len(point)
    else:
        err_msg = f"Unsupported type for point={point}"
        logging.error(err_msg)
        raise TypeError(err_msg)

def signal_handler(sig, frame):
    logging.info(f"Received signal {sig}, shutting down gracefully...")
    sys.exit(1)  # Non-zero so Slurm marks the job as FAILED, not COMPLETED
